---
title: "DS 440 EDA"
output: html_notebook
---

```{r}
# Set working directory
wd <- "C:/Users/malco/Documents/GitHub/DS440/" # change as needed
```

Packages    
```{r}
library(dplyr)
```

# we should convert this to a normal R script

Data Step:

```{r}
batter2020 <- read.csv(paste0(wd, "project/volume/data/raw/sc_2020.csv"))
batter2020 <- rename(batter2020, player_id = batter)
batter2021 <- read.csv(paste0(wd, "project/volume/data/raw/sc_2021.csv"))
batter2021 <- rename(batter2021, player_id = batter)
batter2022 <- read.csv(paste0(wd, "project/volume/data/raw/sc_2022.csv"))
batter2022 <- rename(batter2022, player_id = batter)
batter2023 <- read.csv(paste0(wd, "project/volume/data/raw/sc_2023.csv"))
batter2023 <- rename(batter2023, player_id = batter)
```

```{r}
sprintspeed20 <- read.csv(paste0(wd,"project/volume/data/raw/sprint_speed_2020.csv"))
sprintspeed21 <- read.csv(paste0(wd,"project/volume/data/raw/sprint_speed_2021.csv"))
sprintspeed22 <- read.csv(paste0(wd,"project/volume/data/raw/sprint_speed_2022.csv"))
sprintspeed23 <- read.csv(paste0(wd,"project/volume/data/raw/sprint_speed_2023.csv"))
```

```{r}
total2020 <- merge(batter2020, sprintspeed20, by = "player_id", all.x = T)
total2021 <- merge(batter2021, sprintspeed21, by = "player_id", all.x = T)
total2022 <- merge(batter2022, sprintspeed22, by = "player_id", all.x = T)
total2023 <- merge(batter2023, sprintspeed23, by = "player_id", all.x = T)
master <- rbind(total2020, total2021, total2022, total2023)
in_play <- subset(master, bb_type %in% c("ground_ball", "fly_ball", "line_drive", "popup"))
```

Feature engineer spray angle
```{r}
spray_angle <- with(in_play, round(
  (atan(
    (hc_x-125.42)/(198.27-hc_y)
   )*180/pi*.75)
  ,1))
in_play$spray_angle <- spray_angle
head(in_play, 25)
```

Cleaning
```{r}
bip_raw <- subset(in_play, select = c(
  "player_id", "game_year", "player_name", "stand", "events", "bb_type", "woba_value",
  "launch_speed", "launch_angle", "spray_angle", "sprint_speed"
))
```

Writing Data
```{r}
write.csv(bip_raw, paste0(wd,"project/volume/data/interim/bip_raw.csv"), row.names = FALSE)
```

